#datasource
datasource:
  url: jdbc:mysql://localhost:3306/lzj_app?serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
server.port: 8080

logging:
  file:
    path: ./logs

#ebean
ebean:
  db:
    ddl:
      generate: false
      run:  false
    search:
      packages: com.core.domain
  migration:
    run: false

spring:
  #thymeleaf
  hymeleaf:
    mode: html
    cache: false
core:
  security:
    key: 0161df832b464d2eaca0d4fccaa0e14f
